### ISSUE TITLE
Broken link to "papers" in the README

### ISSUE THREAD

**Issue by mbrukman** [eugeneyan/applyingml#17]
In the README, the "papers" link which points to https://applyingml.com/applied-ml/ is returning 404:

https://github.com/eugeneyan/applyingml/blob/ae986d3a3b307c83093a5e3ba299bb02e10d2263/README.md#L3

shows:

> ## ApplyingML
>
> Opps, page not found.

**Comment by eugeneyan** [comment]
Thanks for raising this—fixed!

**Comment by mbrukman** [comment]
Thank you for the quick fix! And thank you for building and sharing this website and your other repos with us!
