### ISSUE TITLE
Update URL https://github.com/eugeneyan/applied-ml/blob/master/CONTRIBUTING.md since default branch was renamed `master` → `main`

### ISSUE THREAD

**Issue by mbrukman** [eugeneyan/applyingml#18]
https://github.com/eugeneyan/applied-ml/blob/master/CONTRIBUTING.md redirects to
https://github.com/eugeneyan/applied-ml/blob/main/CONTRIBUTING.md so in the following file, the `/master/` part of the URL should be updated to `/main/` since the branch was renamed:

https://github.com/eugeneyan/applyingml/blob/352e9e0e8d8899b98ec80f79a8147459a64275e1/src/assets/applied-ml.mdx#L12

**Comment by eugeneyan** [comment]
Fixed!
